version: '3.8'

services:
  geo-loc-react:
    container_name: geo-loc-react
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    env_file:
      - ./.env.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true
